n = input('Digite um valor:')
#Metodo is 
print(n.isalpha())
print(n.isalnum())
print(n.isascii())
print(n.isdecimal())
print(n.isdigit())
print(n.isidentifier())
print(n.islower())
print(n.isnumeric())
print(n.isprintable())
print(n.isspace())
print(n.istitle())
print(n.isupper())